### ISSUE TITLE
Adapt zerowriter to 2in9v2 display

### ISSUE THREAD

**Issue by Uri0533** [zerowriter/zerowriter1#6]
Is this something that can be done easily?
Can you give guidance on what needs to be changed in the code?

Thanks in advance!

**Comment by zerowriter** [comment]
Hello -- I would think this is pretty straight forward.

I'll be updating the main codebase to the 4in2v2 driver soon. it looks like it has a lot of common syntax with the 2in9v2, so you might be able to drop it in, modify some resolution code / characters per line, and be done with it.

I don't have a 2in9v2 myself to test, and I am not interested in this, so someone else may have to do the testing there... but it shouldn't be too bad.

**Comment by zerowriter** [comment]
Not sure if you have been following, but there is a 2.2 branch that should have very similar driver code you could build from now.

**Comment by SiderBright** [comment]
Hey, could you point me in the right direction to start modifying stuff for another screen? I have a 2.13 from a pwnagotchi project and i would love to have a keychain zero writer

**Comment by zerowriter** [comment]
Hello!

I would look at the github for waveshare:
https://github.com/waveshareteam/e-Paper/blob/master/RaspberryPi_JetsonNano/python/examples/epd_2in13_V4_test.py
for your particular display - not sure which version of the 2.13 you have.
And then you can plug in your display driver instead of the 4.2: 'from
waveshare_epd import epd2in13_V4' . Then, look to replace the full update
and partial update functions with the syntax your new driver needs.

You'd also want to modify the resolution, chars_per_line, etc to match more
closely what the 2in13 needs.
